### ISSUE TITLE
Error MODE 1 (no output frames, only folder created)

### ISSUE THREAD

**Issue by Jan-t2b-filip** [ChlupacTheBosmer/ICVT#11]
Flow: Text detection failed - L46 2022/04/23 14:50527
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\janfi\miniconda3\envs\vid_env\ICVT\crop.py", line 964, in <lambda>
    crop_button = tk.Button(bottom_toolbar, text="Crop", image=crop_icon, compound=tk.LEFT, padx=10, pady=5, width=300, height=48, command=lambda j=j: crop_engine())
  File "C:\Users\janfi\miniconda3\envs\vid_env\ICVT\crop.py", line 1057, in crop_engine
    video_data = get_video_data(video_filepaths)
  File "C:\Users\janfi\miniconda3\envs\vid_env\ICVT\crop.py", line 551, in get_video_data
    video_start_time, video_end_time = get_video_start_end_times(video_filepaths[i])
  File "C:\Users\janfi\miniconda3\envs\vid_env\ICVT\crop.py", line 400, in get_video_start_end_times
    start_time_seconds = process_OCR_text(text, frame)
  File "C:\Users\janfi\miniconda3\envs\vid_env\ICVT\crop.py", line 340, in process_OCR_text
    screen_width = root.winfo_screenwidth()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1252, in winfo_screenwidth
    self.tk.call('winfo', 'screenwidth', self._w))
_tkinter.TclError: can't invoke "winfo" command: application has been destroyed

**Comment by ChlupacTheBosmer** [comment]
For some reason, the root window was destroyed while it was called to obtain the screen size. This is unexpected as the root window is destroyed only for a brief moment when submitting OCR manual read-out time. It is immediately restarted but possibly before it gets created the OCR text processing function is advancing independently.

For user: 
@Jan-t2b-filip 
Report if fixed.
If this happens again, please report whether this was before the first OCR read-out window or after the first one was closed.

**Comment by Jan-t2b-filip** [comment]
@ChlupacTheBosmer 

Not working MODE 1

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\janfi\miniconda3\envs\vid_env\ICVT\crop.py", line 1060, in <lambda>
    height=48, command=lambda j=j: crop_engine())
  File "C:\Users\janfi\miniconda3\envs\vid_env\ICVT\crop.py", line 1160, in crop_engine
    annotation_data_array = load_csv(annotation_file_path)
  File "C:\Users\janfi\miniconda3\envs\vid_env\ICVT\crop.py", line 506, in load_csv
    filtered_df = pd.read_excel(file_path, usecols=cols, skiprows=2, header=None,
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\excel\_base.py", line 486, in read_excel
    data = io.parse(
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\excel\_base.py", line 1551, in parse
    return self._reader.parse(
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\excel\_base.py", line 751, in parse
    data = self.get_sheet_data(sheet, file_rows_needed)
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\excel\_openpyxl.py", line 602, in get_sheet_data
    for row_number, row in enumerate(sheet.rows):
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\worksheet\_read_only.py", line 81, in _cells_by_row
    for idx, row in parser.parse():
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\worksheet\_reader.py", line 163, in parse
    obj = prop[1].from_tree(element)
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\descriptors\serialisable.py", line 87, in from_tree
    obj = desc.expected_type.from_tree(el)
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\descriptors\serialisable.py", line 87, in from_tree
    obj = desc.expected_type.from_tree(el)
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\descriptors\serialisable.py", line 87, in from_tree
    obj = desc.expected_type.from_tree(el)
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\descriptors\serialisable.py", line 103, in from_tree
    return cls(**attrib)
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\worksheet\filters.py", line 184, in __init__
    self.val = val
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\worksheet\filters.py", line 165, in __set__
    raise ValueError("Value must be either numerical or a string containing a wildcard")
ValueError: Value must be either numerical or a string containing a wildcard
