### ISSUE TITLE
Not able to run MODE 1 

### ISSUE THREAD

**Issue by Jan-t2b-filip** [ChlupacTheBosmer/ICVT#12]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\janfi\miniconda3\envs\vid_env\ICVT\crop.py", line 376, in <lambda>
    submit_button = tk.Button(dialog, text="Submit", font=("Arial", 10), command=lambda j=j: submit_time(input_field))
  File "C:\Users\janfi\miniconda3\envs\vid_env\ICVT\crop.py", line 314, in submit_time
    dialog.destroy()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 2609, in destroy
    self.tk.call('destroy', self._w)
_tkinter.TclError: can't invoke "destroy" command: application has been destroyed
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\janfi\miniconda3\envs\vid_env\ICVT\crop.py", line 964, in <lambda>
    crop_button = tk.Button(bottom_toolbar, text="Crop", image=crop_icon, compound=tk.LEFT, padx=10, pady=5, width=300, height=48, command=lambda j=j: crop_engine())
  File "C:\Users\janfi\miniconda3\envs\vid_env\ICVT\crop.py", line 1058, in crop_engine
    annotation_data_array = load_excel_table(annotation_file_path)
  File "C:\Users\janfi\miniconda3\envs\vid_env\ICVT\crop.py", line 429, in load_excel_table
    df = pd.read_excel(file_path, usecols=cols, skiprows=2, header=None, converters={0: evaluate_string_formula, 1: evaluate_string_formula, 2: evaluate_string_formula, 3: evaluate_string_formula, 4: evaluate_string_formula, 18: evaluate_string_formula})
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\excel\_base.py", line 486, in read_excel
    data = io.parse(
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\excel\_base.py", line 1551, in parse
    return self._reader.parse(
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\excel\_base.py", line 751, in parse
    data = self.get_sheet_data(sheet, file_rows_needed)
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\excel\_openpyxl.py", line 602, in get_sheet_data
    for row_number, row in enumerate(sheet.rows):
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\worksheet\_read_only.py", line 81, in _cells_by_row
    for idx, row in parser.parse():
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\worksheet\_reader.py", line 163, in parse
    obj = prop[1].from_tree(element)
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\descriptors\serialisable.py", line 87, in from_tree
    obj = desc.expected_type.from_tree(el)
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\descriptors\serialisable.py", line 87, in from_tree
    obj = desc.expected_type.from_tree(el)
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\descriptors\serialisable.py", line 87, in from_tree
    obj = desc.expected_type.from_tree(el)
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\descriptors\serialisable.py", line 103, in from_tree
    return cls(**attrib)
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\worksheet\filters.py", line 184, in __init__
    self.val = val
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\worksheet\filters.py", line 165, in __set__
    raise ValueError("Value must be either numerical or a string containing a wildcard")
ValueError: Value must be either numerical or a string containing a wildcard

**Comment by Jan-t2b-filip** [comment]
Mistakes in the input Excel tables.

**Comment by ChlupacTheBosmer** [comment]
@Jan-t2b-filip Please describe the mistakes. Is it worth fixing for the future or was this just one time anomaly?
