### ISSUE TITLE
Crop.py Excel file issues

### ISSUE THREAD

**Issue by ChlupacTheBosmer** [ChlupacTheBosmer/ICVT#17]
@ChlupacTheBosmer 

Not working MODE 1

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\janfi\miniconda3\envs\vid_env\ICVT\crop.py", line 1060, in <lambda>
    height=48, command=lambda j=j: crop_engine())
  File "C:\Users\janfi\miniconda3\envs\vid_env\ICVT\crop.py", line 1160, in crop_engine
    annotation_data_array = load_csv(annotation_file_path)
  File "C:\Users\janfi\miniconda3\envs\vid_env\ICVT\crop.py", line 506, in load_csv
    filtered_df = pd.read_excel(file_path, usecols=cols, skiprows=2, header=None,
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\excel\_base.py", line 486, in read_excel
    data = io.parse(
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\excel\_base.py", line 1551, in parse
    return self._reader.parse(
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\excel\_base.py", line 751, in parse
    data = self.get_sheet_data(sheet, file_rows_needed)
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\excel\_openpyxl.py", line 602, in get_sheet_data
    for row_number, row in enumerate(sheet.rows):
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\worksheet\_read_only.py", line 81, in _cells_by_row
    for idx, row in parser.parse():
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\worksheet\_reader.py", line 163, in parse
    obj = prop[1].from_tree(element)
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\descriptors\serialisable.py", line 87, in from_tree
    obj = desc.expected_type.from_tree(el)
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\descriptors\serialisable.py", line 87, in from_tree
    obj = desc.expected_type.from_tree(el)
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\descriptors\serialisable.py", line 87, in from_tree
    obj = desc.expected_type.from_tree(el)
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\descriptors\serialisable.py", line 103, in from_tree
    return cls(**attrib)
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\worksheet\filters.py", line 184, in __init__
    self.val = val
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\worksheet\filters.py", line 165, in __set__
    raise ValueError("Value must be either numerical or a string containing a wildcard")
ValueError: Value must be either numerical or a string containing a wildcard

_Originally posted by @Jan-t2b-filip in https://github.com/ChlupacTheBosmer/ICVT/issues/11#issuecomment-1522939273_

**Comment by ChlupacTheBosmer** [comment]
Not working MODE 1

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\janfi\miniconda3\envs\vid_env\ICVT\crop.py", line 1060, in <lambda>
    height=48, command=lambda j=j: crop_engine())
  File "C:\Users\janfi\miniconda3\envs\vid_env\ICVT\crop.py", line 1160, in crop_engine
    annotation_data_array = load_csv(annotation_file_path)
  File "C:\Users\janfi\miniconda3\envs\vid_env\ICVT\crop.py", line 506, in load_csv
    filtered_df = pd.read_excel(file_path, usecols=cols, skiprows=2, header=None,
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\excel\_base.py", line 486, in read_excel
    data = io.parse(
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\excel\_base.py", line 1551, in parse
    return self._reader.parse(
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\excel\_base.py", line 751, in parse
    data = self.get_sheet_data(sheet, file_rows_needed)
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pandas\io\excel\_openpyxl.py", line 602, in get_sheet_data
    for row_number, row in enumerate(sheet.rows):
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\worksheet\_read_only.py", line 81, in _cells_by_row
    for idx, row in parser.parse():
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\worksheet\_reader.py", line 163, in parse
    obj = prop[1].from_tree(element)
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\descriptors\serialisable.py", line 87, in from_tree
    obj = desc.expected_type.from_tree(el)
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\descriptors\serialisable.py", line 87, in from_tree
    obj = desc.expected_type.from_tree(el)
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\descriptors\serialisable.py", line 87, in from_tree
    obj = desc.expected_type.from_tree(el)
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\descriptors\serialisable.py", line 103, in from_tree
    return cls(**attrib)
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\worksheet\filters.py", line 184, in __init__
    self.val = val
  File "C:\Users\janfi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\openpyxl\worksheet\filters.py", line 165, in __set__
    raise ValueError("Value must be either numerical or a string containing a wildcard")
ValueError: Value must be either numerical or a string containing a wildcard

_Originally posted by @Jan-t2b-filip in https://github.com/ChlupacTheBosmer/ICVT/issues/11#issuecomment-1522939273_

**Comment by ChlupacTheBosmer** [comment]
> 

This seems to be caused by filters being applied to the relevant cells. Possibly include an excel preprocessing stage to remove filters.
