### ISSUE TITLE
Crop.py - these two Excels cause error: Defining usecols without of bounds indices is not allowed.

### ISSUE THREAD

**Issue by MichalBartak** [ChlupacTheBosmer/ICVT#42]
[GR2_L5_CreSet2.xlsx](https://github.com/ChlupacTheBosmer/ICVT/files/12358345/GR2_L5_CreSet2.xlsx)
[GR2_L3_TolUmb3.xlsx](https://github.com/ChlupacTheBosmer/ICVT/files/12358347/GR2_L3_TolUmb3.xlsx)

ERROR: Error reading Excel file C:/Users/barta/Desktop/GR2/GR2_L5_CreSet2/GR2_L5_CreSet2.xlsx. Error message: Defining usecols without of bounds indices is not allowed. [40, 46, 47, 48, 49] are out of bounds. (sheet: 0)
ERROR: Error reading Excel file C:/Users/barta/Desktop/GR2/GR2_L5_CreSet2/GR2_L5_CreSet2.xlsx. Error message: Defining usecols without of bounds indices is not allowed. [40, 46, 47, 48, 49] are out of bounds. (sheet: 0)
ERROR: Attempted to fix errors in Excel file C:/Users/barta/Desktop/GR2/GR2_L5_CreSet2/GR2_L5_CreSet2.xlsx. Attempt failed. Error message: Defining usecols without of bounds indices is not allowed. [40, 46, 47, 48, 49] are out of bounds. (sheet: 0). Please fix the errors manually and try again.
ERROR: Attempted to fix errors in Excel file C:/Users/barta/Desktop/GR2/GR2_L5_CreSet2/GR2_L5_CreSet2.xlsx. Attempt failed. Error message: Defining usecols without of bounds indices is not allowed. [40, 46, 47, 48, 49] are out of bounds. (sheet: 0). Please fix the errors manually and try again.
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\barta\miniconda3\envs\ICVT1\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\barta\miniconda3\envs\ICVT1\ICVT\iccs.py", line 1013, in <lambda>
    height=48, command=lambda j=j: self.crop_engine())
                                   ^^^^^^^^^^^^^^^^^^
  File "C:\Users\barta\miniconda3\envs\ICVT1\ICVT\iccs.py", line 556, in crop_engine
    excel = anno_data.Annotation_watcher_file(self.annotation_file_path, True, True, True, True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\barta\miniconda3\envs\ICVT1\ICVT\anno_data.py", line 166, in __init__
    self.dataframe = self.construct_dataframe()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\barta\miniconda3\envs\ICVT1\ICVT\anno_data.py", line 262, in construct_dataframe
    dataframe.rename(columns=column_mapping, inplace=True)
    ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'rename'

**Comment by ChlupacTheBosmer** [comment]
@MichalBartak These Excel files are missing several columns. In the current commit (accessible by git pull) I have added an example excel sheet (~/resources/exc/example_sheet.xlsx) with the right configuration of columns which was supposed to be standardized. You can always check whether the configuration is not altered in the faulty table. 

I guess the best solution is to just add some columns right after the "comments" column so the configuration matches the correct one. There is hardly anything I can do about. I could search for columns by their name but the names of the columns are scrambled more often than their overall configuration. 

Thank you for the report.
